version = 0.1

[default]
[default.build]
[default.build.parameters]
cached = true
parallel = true

[default.validate]
[default.validate.parameters]
lint = true

[default.deploy]
[default.deploy.parameters]
stack_name = "de-palma-dev"
s3_bucket = "" # Will be created automatically
s3_prefix = "de-palma"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
    "Environment=dev"
]

[dev]
[dev.build]
[dev.build.parameters]
cached = true
parallel = true

[dev.deploy]
[dev.deploy.parameters]
stack_name = "de-palma-dev"
s3_bucket = "" # Will be created automatically
s3_prefix = "de-palma-dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
    "Environment=dev",
    "EmailDomain=depalma.work"
]

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "de-palma-prod"
s3_bucket = "" # Will be created automatically
s3_prefix = "de-palma-prod"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
    "Environment=prod",
    "EmailDomain=depalma.work"
]